services:
  petclinic-postgres:
    build: .
    restart: always
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
    depends_on:
      - postgres-db

  petclinic-h2:
    build: .
    restart: always
    ports:
      - "8081:8080"

  postgres-db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: